config/routes.rb
Onemusic::Application.routes.draw do
  
  resources :artists

  resources :playlists

  resources :charges
  resources :songs

  root :to => 'songs#landing'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  

end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :artist_name, :track_title, :uid, :username
  belongs_to :user 

  has_and_belongs_to_many :playlists
  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
#   before_filter :stream
  # GET /songs
  # GET /songs.json
  def index

    #create a client object with your app credentials
    @client = Soundcloud.new(:client_id => ENV['SOUNDCLOUD_CLIENT_ID'])
    #fetch track to stream
    @track = @client.get('/users/52173235/tracks/103621673')
    
    track_url = 'http://soundcloud.com/forss/flickermood'

    @embed_info = @client.get('/oembed', :url => track_url)

    # #get the tracks streaming URL
    @stream_url = @track.stream_url
    # @songs = @stream_url.location
  # print the tracks stream URL
  # puts 
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end

  def landing 
  end 
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist_name %><br />
    <%= f.text_field :artist_name %>
  </div>
  <div class="field">
    <%= f.label :track_title %><br />
    <%= f.text_field :track_title %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.number_field :uid %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<div class="list_songs">
  <h1>Listing songs</h1>
</div>
<script type="text/javascript" src="scripts/soundcloud.player.api.js"></script>
<script type="text/javascript">
   soundcloud.addEventListener('onPlayerReady', function(player, data) {
     player.api_play();
   });
</script>

<!-- <h1>Listing songs</h1>
>>>>>>> 25b6bcf962a99781d046788bc95f07de03e17ade -->

<table>
  <tr>
    <th>Artist name</th>
    <th>Track title</th>
    <th>Uid</th>
    <th>Username</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 </table>
<br />

<object height="81" width="100%" id="myPlayer" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000">
 
  <param name="movie" value="http://player.soundcloud.com/player.swf?url=https://api.soundcloud.com/playlists/8492346&enable_api=true&object_id=myPlayer" buying='true' download='true'></param>
  <param name="allowscriptaccess" value="always"></param>
  
  <embed allowscriptaccess="always" height="81" src="http://player.soundcloud.com/player.swf?url=https://api.soundcloud.com/playlists/8492346&enable_api=true&object_id=myPlayer" type="application/x-shockwave-flash" width="100%" name="myPlayer"></embed>


</object>

// <script>
// <object height="81" width="100%">
//   <param name="movie" 
//     value="http://player.soundcloud.com/player.swf?{ ADD YOUR PARAMETERS HERE }&url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F293"></param>
//   <param name="allowscriptaccess" value="always"></param>
//   <embed 
//     src="http://player.soundcloud.com/player.swf?{ ADD YOUR PARAMETERS HERE }&url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F293" 
//     allowscriptaccess="always" height="81"  type="application/x-shockwave-flash" width="100%">
//   </embed>
// </object>
// </script>

<%= link_to 'New Song', new_song_path %>

app/views/songs/landing.html.erb
<div class="logo-wrapper">
<h1 class="landing-title">The 
      Underground</h1>
<a class="signup" href="#">Sign Up</a>
<a class="signin" href="#">Sign In</a>
</div>

<!-- <div class="main-wrapper">
  <h1 class="logo">U</h1> -->

  <div class="wrapper-listen">
  <h2 class="header-one"> Listen: </h2> 
    <div class="pure-g-r one">
      <div class="pure-u-1-5 listen-info">
        <p> Pick a genre. </p>
      </div>

      <div class="pure-u-1-5 listen-info">
        <p> Browse through the list of new, up and coming artists. </p>
      </div>

      <div class="pure-u-1-5 listen-info">
        <p> Find you favorite artists and tracks. </p>
      </div> 
    </div>
  </div>
<!-- </div>
 -->

  <div class="wrapper-promote">
  <h2 class="header-two"> Promote: </h2> 
    <div class="pure-g-r two">
      <div class="pure-u-1-5 promote-info">
        <p> Listen to your artists. </p>
      </div>

      <div class="pure-u-1-5 promote-info">
        <p> Give them a vote and bring them to your town. </p>
      </div>

      <div class="pure-u-1-5 promote-info">
        <p> Donate to help them make more music. </p>
      </div> 
    </div>
  </div>


  

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Artist name:</b>
  <%= @song.artist_name %>
</p>

<p>
  <b>Track title:</b>
  <%= @song.track_title %>
</p>

<p>
  <b>Uid:</b>
  <%= @song.uid %>
</p>

<p>
  <b>Username:</b>
  <%= @song.username %>
</p>


<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>