config/routes.rb
Onemusic::Application.routes.draw do
  
  resources :artists

  resources :playlists

  resources :charges
  resources :songs

  root :to => 'songs#landing'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  attr_accessible :playlist_id, :uid
  attr_accessor :uid, :path_connect, :fake_url

  belongs_to :user
  has_and_belongs_to_many :songs

  def self.import_for_user(user)
    # to set a user by their uid associated with this playlist
    client = Soundcloud.new(:access_token => user.soundcloud_token)

      # '#{@user.soundcloud_token}')

    # get playlist
    # @path = 'http://soundcloud.com/users/' + self.uid 
    # @path_connect = "https://api.soundcloud.com/playlists/8492346"

    path = '/users/' + user.uid + '/playlists'
    playlists = client.get(path)
    # playlist_id = playlists.id

    # @url = "http://player.soundcloud.com/player.swf?url="+@path_connect+"&enable_api=true&object_id=myPlayer" 


    playlists.each do |pl|
      puts pl.id
      playlist = user.playlists.find_or_initialize_by_soundcloud_id(pl.id)
      playlist.soundcloud_id = pl.id
      playlist.save
      pl.tracks.each do |track|
        puts track.uri
        puts track.id 
        song = playlist.songs.find_or_initialize_by_soundcloud_id(track.id)
        song.user = user
        song.soundcloud_id = track.id
        song.track_title = track.title
        # song.artist_name = track.artist
        song.save
      end
    end

  end

  def soundcloud_url
    "https://api.soundcloud.com/playlists/#{soundcloud_id}"
  end

  def self.return_url
    "https://api.soundcloud.com/playlists/8492346"
  end 

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  attr_accessor :fake_url
  # GET /playlists
  # GET /playlists.json
  def index
    Playlist.import_for_user(current_user)
    @playlists = current_user.playlists.all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    @playlist = Playlist.find(params[:id])
     
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/new
  # GET /playlists/new.json
  def new
    @playlist = Playlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/1/edit
  def edit
    @playlist = Playlist.find(params[:id])
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(params[:playlist])

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render json: @playlist, status: :created, location: @playlist }
      else
        format.html { render action: "new" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /playlists/1
  # PUT /playlists/1.json
  def update
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      if @playlist.update_attributes(params[:playlist])
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to playlists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :playlist_id %><br />
    <%= f.text_field :playlist_id %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<script src="//connect.soundcloud.com/sdk.js"></script>
<script src="https://checkout.stripe.com/v2/checkout.js"></script>

<h1>Listing playlists</h1>


<% @playlists.each do |playlist| %>
<div class="soundcloud" data-soundcloud-url="<%= playlist.soundcloud_url %>">
  <object height="81" width="100%" id="myPlayer" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000">
   
    <param name="movie" value="http://player.soundcloud.com/player.swf?url=<%= playlist.soundcloud_url %>&enable_api=true&object_id=myPlayer" buying='true' download='true'></param>
    <param name="allowscriptaccess" value="always"></param>
    
    <embed allowscriptaccess="always" height="81" src="http://player.soundcloud.com/player.swf?url=<%= playlist.soundcloud_url%>&enable_api=true&object_id=myPlayer" type="application/x-shockwave-flash" width="100%" name="myPlayer"></embed>
  </object>
  </div>
<% end %>

<%= link_to 'New Playlist', new_playlist_path %>

  <%= current_user.username %>

  <form>
	<input type='text' id='stripeDollars' /> 
  <button type='submit' id="customButton">Help Fund!</button>
  </form>

  <script>
    $('#customButton').click(function(){
      var token = function(res){
        var $input = $('<input type="hidden" name=stripeToken />').val(res.id);
        $('form').append($input).submit();
      };
      var money = $('#stripeDollars').val() * 100;
      console.log(money);
      	
      StripeCheckout.open({
        key:        "<%= Rails.configuration.stripe[:stripe_publishable_key] %>",
        address:     true,
        amount:      money,
        currency:    'usd',
        panelLabel:  'Checkout',
        token:       token
      });
      return false;
    });
  </script>

app/views/playlists/new.html.erb
<h1>New playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Playlist:</b>
  <%= @playlist.playlist_id %>
</p>

<p>
  <b>Uid:</b>
  <%= @playlist.uid %>
</p>


<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>